#define app engine deployment

runtime: python39
entrypoint: gunicorn -b :$PORT --chdir app/ app.wsgi:application

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

env_variables:
    APPENGINE_URL: https://yourairport.uc.r.appspot.com